### ISSUE TITLE
 depthhai-core and libusb Cmakelists.txt configuration error

### ISSUE THREAD

**Issue by danniu1314** [onuralpszr/DepthAiAndroidToolbox#5]
Hello, I would like to ask about the depthhai-core and libusb in cpp. There is no code after git pulls the code. After jumping to another project to download the code, and directly copying it to the project, a configuration error in cmakelists.txt will occur. Could you also upload the complete code for this one?

And I hope to have a complete demo of the OAK camera call. thank you

**Comment by onuralpszr** [comment]
> Hello, I would like to ask about the depthhai-core and libusb in cpp. There is no code after git pulls the code. After jumping to another project to download the code, and directly copying it to the project, a configuration error in cmakelists.txt will occur. Could you also upload the complete code for this one?
> 
> And I hope to have a complete demo of the OAK camera call. thank you

Could you show me what error you getting into it. It seems to be you should do `git submodule update --init --recursive` after you clone the code because It works fine in here.

**Comment by danniu1314** [comment]
The log has been sent in the mailbox, and we hope to receive your reply. Thank you

**Comment by onuralpszr** [comment]
Hello @danniu1314 first of all "images" was missing not showed up. I checked error and that is a windows based on problem because I don't have this issue at all. Plus you don't add this project as a dependency. Because this is an APP not an library or module, so you used as it is. Also you said "git never pulled" I don't understand what never pulled. But for you to show, I just made a github-action in my project (I was already planning so I just did anyway) 

This is the [last action](https://github.com/onuralpszr/DepthAiAndroidToolbox/actions/runs/4467963374) it has "debug-apk" so you can try it. 

Also I have to some fair warnings, 

- Use a proper usb cable (not every cable works in the same way you gonna have to make sure that)
- I tested on OAK-D Lite and OAK-D (not the pro one) so both them works. 
- It should ask "permission" more than once (it is a known bug I am also looking as well) 
- Please check your windows system and android studio because that escape character not something I see in here but most likely it is a "encode" problem on your system (that is my guess)

**Comment by danniu1314** [comment]
thank you very much

**Comment by danniu1314** [comment]
hello @onuralpszr App has anr on Android 13,App cannot pull up camera on Android 12。I have sent the log file to your mailbox。
Thank you very much for your patient answer.
